default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: home_test_app_development

test:
  <<: *default
  database: home_test_app_test

production:
  <<: *default
  database: home_test_app_production
